- id: namespell
  name: Name spellchecker
  description: Check name spelling (case-sensitive)
  entry: namespell
  language: python

- id: sort-mkdocs
  name: Sorts mkdocs.yml file
  description: Sorts mkdocs.yml file
  entry: sort-mkdocs
  language: python

- id: check-upstream-status
  name: Upstream-Status checker
  description: Check Upstream-Status tag in a commit message
  entry: check-upstream-status
  language: python
  stages: [commit-msg]
  always_run: true
  pass_filenames: false

- id: replace-hyphen-like
  name: Replace hyphen-like characters with HYPHEN-MINUS in markdown
  entry: replace-hyphen-like
  language: system
  files: \.(md|markdown)$
  types: [text]
  pass_filenames: true
